# Generated by Django 5.1.3 on 2024-11-26 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bounty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bounty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('previous_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('last_updated', models.DateTimeField(verbose_name='Last Updated')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(max_length=200)),
                ('card_mp', models.DecimalField(decimal_places=2, max_digits=15)),
                ('card_rarity', models.CharField(max_length=200)),
                ('card_desc', models.CharField(max_length=200)),
                ('card_color', models.CharField(max_length=200)),
                ('card_cost', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Bounties',
        ),
        migrations.AddField(
            model_name='bounty',
            name='card_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bounty.card'),
        ),
    ]
