# Generated by Django 5.1.3 on 2024-12-02 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bounty', '0002_bounty_card_delete_bounties_bounty_card_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='card_color',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='card_cost',
            new_name='cost',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='card_desc',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='card_mp',
            new_name='mp',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='card_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='card_rarity',
            new_name='rarity',
        ),
    ]
